### ISSUE TITLE
后端设计与开发1

### ISSUE THREAD

**Issue by cccchangnian** [wutcst/sept2-wuwu#2]
## 背景描述

World of Zuul是一款文字冒险游戏，玩家需要通过命令与游戏进行交互，探索游戏世界并完成各种任务。
world-of-zull是由will Crowther在20世纪70年代开发、并经过Don woods扩充的一个探险游戏。原版的游戏有时候也叫作巨洞探险(Colossal Cave Adventure）。在那个时代可是一个精彩的、充满想象力的复杂游戏，包括要在一个复杂的洞穴系统中找到出路、寻找隐藏的财宝、使用暗语和其他一些神秘的工具，最终的目的是获得高分。

## 任务要求
本项目的后端部分旨在基于Java、Spring Boot和Maven等实现具体的游戏命令逻辑。
### 技术要求

- Java
- Spring Boot
- Maven
- 数据库（如MySQL等）

#### 实现"go"功能

- 设计并实现与移动命令相关的API接口，接收玩家的移动指令并进行相应的处理。
- 根据玩家的当前位置和目标位置，更新玩家的位置信息，并返回相应的结果。

#### 实现"look"功能

- 设计并实现与查看命令相关的API接口，接收玩家的查看指令并进行相应的处理。
- 根据玩家的当前位置，返回当前房间的描述信息、可见物品等相关信息。

#### 实现"items"功能

- 设计并实现与查看物品命令相关的API接口，接收玩家的查看物品指令并进行相应的处理。
- 根据玩家的当前位置，返回当前房间中的可见物品列表。

#### 实现"take"功能

- 设计并实现与捡起命令相关的API接口，接收玩家的捡起指令并进行相应的处理。
- 根据玩家的当前位置和指定的物品，更新玩家的物品列表和房间的物品列表。

#### 实现"drop"功能

- 设计并实现与放下命令相关的API接口，接收玩家的放下指令并进行相应的处理。
- 根据玩家的当前位置和指定的物品，更新玩家的物品列表和房间的物品列表。

**注意：**

- 在开始开发之前，请仔细阅读：
  - 分支管理规范文档
  - 提交规范文档
  - 前后端接口规范文档
  - 任务分工文档
  - issue说明。

- 如果有问题，请及时联系组长。

**Comment by wangyuze18** [comment]
后端任务基本完成
